[tool.commitizen]
# Reference: https://commitizen-tools.github.io/commitizen/config/
name = "cz_conventional_commits"
version_scheme = "pep440"
version_provider = "pep621"
update_changelog_on_bump = true
major_version_zero = true
changelog_file = "docs/changelog.md"
tag_format = "v$version"
