site_name: Template Project
theme:
  name: material
plugins:
  - search:
  - pdf-export:
      verbose: false
      media_type: print
      combined: true
      enabled_if_env: ENABLE_PDF_EXPORT
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: google

nav:
  - Home: index.md
  - Python: python.md
  - Invoke Tasks: tasks.md
  - Changelog: changelog.md
