name: Create GitHub Release

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    types: [closed]
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tag_commit:
    name: Tag Commit
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Extract version from head branch
        id: get_tag
        env:
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          TAG_NAME=$(echo "$PR_HEAD_REF" | sed -e 's/release\///')
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create tag
        env:
          TAG_NAME: ${{ steps.get_tag.outputs.TAG_NAME }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"

  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    steps:
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-interaction --no-ansi --only main

      - name: Build package
        run: poetry run invoke python.build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          body: |
            ### Changes

          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: dist/*.whl
