name: Tag the next release

on:
  pull_request:
    types: [closed]
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tag_commit:
    name: Tag Commit
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Extract version from head branch
        id: get_tag
        env:
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          TAG_NAME=$(echo "$PR_HEAD_REF" | sed -e 's/release\///')
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create tag
        env:
          TAG_NAME: ${{ steps.get_tag.outputs.TAG_NAME }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"
